import { Ruangan, Kamar, Bed, Patient, PatientMovement, ReconciliationSession, HospitalConfig, AuditLog } from './types';

export const INITIAL_CONFIG: HospitalConfig = {
  namaRumahSakit: 'RS Umum Daerah Medika Husada',
  namaFaskesSub: 'Sistem Informasi Mutasi & Tracking Bed (SIMUTASIS)',
  kodeFaskes: 'RS-3171092',
  alamat: 'Jl. Kesehatan Raya No. 45, Jakarta Pusat',
  telepon: '(021) 3928-1002',
  zonaWaktu: 'Asia/Jakarta (WIB)',
  shiftRekonsiliasi: ['08.00 WIB', '14.00 WIB', '20.00 WIB'],
  autoAlertEnabled: true,
  overcapacityThreshold: 85,
};

export const INITIAL_ROOMS: Ruangan[] = [
  {
    id: 'R-MELATI',
    namaRuangan: 'Ruang Melati (Kelas 1)',
    kodeRuangan: 'MEL',
    kelas: 'Kelas 1',
    gedung: 'Gedung A',
    lantai: 2,
    pjRuangan: 'Ns. Ratna Dewi, S.Kep',
    kapasitasMaksimal: 8,
  },
  {
    id: 'R-MAWAR',
    namaRuangan: 'Ruang Mawar (Kelas 2)',
    kodeRuangan: 'MAW',
    kelas: 'Kelas 2',
    gedung: 'Gedung A',
    lantai: 3,
    pjRuangan: 'Ns. Hendra Wijaya, S.Kep',
    kapasitasMaksimal: 10,
  },
  {
    id: 'R-TERATAI',
    namaRuangan: 'Ruang Teratai (Kelas 3)',
    kodeRuangan: 'TER',
    kelas: 'Kelas 3',
    gedung: 'Gedung B',
    lantai: 1,
    pjRuangan: 'Ns. Sri Wahyuni, S.Kep',
    kapasitasMaksimal: 12,
  },
  {
    id: 'R-ANGGREK',
    namaRuangan: 'Ruang Anggrek (VIP)',
    kodeRuangan: 'ANG',
    kelas: 'VIP',
    gedung: 'Gedung Paviliun',
    lantai: 2,
    pjRuangan: 'Ns. Maya Indah, S.Kep',
    kapasitasMaksimal: 6,
  },
  {
    id: 'R-EDELWEISS',
    namaRuangan: 'Ruang Edelweiss (VVIP)',
    kodeRuangan: 'EDL',
    kelas: 'VVIP',
    gedung: 'Gedung Paviliun',
    lantai: 3,
    pjRuangan: 'Ns. Dian Anggraini, S.Kep',
    kapasitasMaksimal: 4,
  },
  {
    id: 'R-ICU',
    namaRuangan: 'ICU (Intensive Care Unit)',
    kodeRuangan: 'ICU',
    kelas: 'Intensif',
    gedung: 'Gedung Utama',
    lantai: 2,
    pjRuangan: 'Ns. Fajar Pratama, S.Kep',
    kapasitasMaksimal: 6,
  },
  {
    id: 'R-ISOLASI',
    namaRuangan: 'Ruang Isolasi Flamboyan',
    kodeRuangan: 'FLA',
    kelas: 'Isolasi',
    gedung: 'Gedung C',
    lantai: 1,
    pjRuangan: 'Ns. Eka Suryani, S.Kep',
    kapasitasMaksimal: 6,
  },
];

export const INITIAL_KAMAR: Kamar[] = [
  // Melati (8 beds total)
  { id: 'K-MEL-101', namaKamar: 'Kamar 101', ruanganId: 'R-MELATI', kelas: 'Kelas 1', totalBed: 2 },
  { id: 'K-MEL-102', namaKamar: 'Kamar 102', ruanganId: 'R-MELATI', kelas: 'Kelas 1', totalBed: 2 },
  { id: 'K-MEL-103', namaKamar: 'Kamar 103', ruanganId: 'R-MELATI', kelas: 'Kelas 1', totalBed: 2 },
  { id: 'K-MEL-104', namaKamar: 'Kamar 104', ruanganId: 'R-MELATI', kelas: 'Kelas 1', totalBed: 2 },

  // Mawar (10 beds total)
  { id: 'K-MAW-201', namaKamar: 'Kamar 201', ruanganId: 'R-MAWAR', kelas: 'Kelas 2', totalBed: 4 },
  { id: 'K-MAW-202', namaKamar: 'Kamar 202', ruanganId: 'R-MAWAR', kelas: 'Kelas 2', totalBed: 4 },
  { id: 'K-MAW-203', namaKamar: 'Kamar 203', ruanganId: 'R-MAWAR', kelas: 'Kelas 2', totalBed: 2 },

  // Teratai (12 beds total)
  { id: 'K-TER-301', namaKamar: 'Kamar 301', ruanganId: 'R-TERATAI', kelas: 'Kelas 3', totalBed: 6 },
  { id: 'K-TER-302', namaKamar: 'Kamar 302', ruanganId: 'R-TERATAI', kelas: 'Kelas 3', totalBed: 6 },

  // Anggrek VIP (6 beds total - single)
  { id: 'K-ANG-401', namaKamar: 'VIP Suite 401', ruanganId: 'R-ANGGREK', kelas: 'VIP', totalBed: 1 },
  { id: 'K-ANG-402', namaKamar: 'VIP Suite 402', ruanganId: 'R-ANGGREK', kelas: 'VIP', totalBed: 1 },
  { id: 'K-ANG-403', namaKamar: 'VIP Suite 403', ruanganId: 'R-ANGGREK', kelas: 'VIP', totalBed: 1 },
  { id: 'K-ANG-404', namaKamar: 'VIP Suite 404', ruanganId: 'R-ANGGREK', kelas: 'VIP', totalBed: 1 },
  { id: 'K-ANG-405', namaKamar: 'VIP Suite 405', ruanganId: 'R-ANGGREK', kelas: 'VIP', totalBed: 1 },
  { id: 'K-ANG-406', namaKamar: 'VIP Suite 406', ruanganId: 'R-ANGGREK', kelas: 'VIP', totalBed: 1 },

  // Edelweiss VVIP (4 beds total - single)
  { id: 'K-EDL-501', namaKamar: 'Presidential 501', ruanganId: 'R-EDELWEISS', kelas: 'VVIP', totalBed: 1 },
  { id: 'K-EDL-502', namaKamar: 'Presidential 502', ruanganId: 'R-EDELWEISS', kelas: 'VVIP', totalBed: 1 },
  { id: 'K-EDL-503', namaKamar: 'Presidential 503', ruanganId: 'R-EDELWEISS', kelas: 'VVIP', totalBed: 1 },
  { id: 'K-EDL-504', namaKamar: 'Presidential 504', ruanganId: 'R-EDELWEISS', kelas: 'VVIP', totalBed: 1 },

  // ICU (6 beds)
  { id: 'K-ICU-601', namaKamar: 'ICU Unit A', ruanganId: 'R-ICU', kelas: 'Intensif', totalBed: 3 },
  { id: 'K-ICU-602', namaKamar: 'ICU Unit B', ruanganId: 'R-ICU', kelas: 'Intensif', totalBed: 3 },

  // Isolasi (6 beds)
  { id: 'K-ISO-701', namaKamar: 'Isolasi Negatif 701', ruanganId: 'R-ISOLASI', kelas: 'Isolasi', totalBed: 2 },
  { id: 'K-ISO-702', namaKamar: 'Isolasi Tekanan 702', ruanganId: 'R-ISOLASI', kelas: 'Isolasi', totalBed: 2 },
  { id: 'K-ISO-703', namaKamar: 'Isolasi Khusus 703', ruanganId: 'R-ISOLASI', kelas: 'Isolasi', totalBed: 2 },
];

export const INITIAL_BEDS: Bed[] = [
  // Melati (8 beds)
  { id: 'BED-MEL-101-1', nomorBed: 'B-101-1', kamarId: 'K-MEL-101', ruanganId: 'R-MELATI', status: 'TERISI', patientId: 'PAT-001', updatedAt: '2026-09-30 08:30' },
  { id: 'BED-MEL-101-2', nomorBed: 'B-101-2', kamarId: 'K-MEL-101', ruanganId: 'R-MELATI', status: 'TERISI', patientId: 'PAT-002', updatedAt: '2026-09-29 11:15' },
  { id: 'BED-MEL-102-1', nomorBed: 'B-102-1', kamarId: 'K-MEL-102', ruanganId: 'R-MELATI', status: 'AKAN_PULANG', patientId: 'PAT-003', updatedAt: '2026-09-28 14:00' },
  { id: 'BED-MEL-102-2', nomorBed: 'B-102-2', kamarId: 'K-MEL-102', ruanganId: 'R-MELATI', status: 'KOSONG', updatedAt: '2026-09-30 06:10' },
  { id: 'BED-MEL-103-1', nomorBed: 'B-103-1', kamarId: 'K-MEL-103', ruanganId: 'R-MELATI', status: 'TERISI', patientId: 'PAT-004', updatedAt: '2026-09-30 09:20' },
  { id: 'BED-MEL-103-2', nomorBed: 'B-103-2', kamarId: 'K-MEL-103', ruanganId: 'R-MELATI', status: 'BOOKING', bookingNote: 'Booking Rujukan IGD dr. Ananta, rencana masuk 15.00 WIB', updatedAt: '2026-09-30 11:00' },
  { id: 'BED-MEL-104-1', nomorBed: 'B-104-1', kamarId: 'K-MEL-104', ruanganId: 'R-MELATI', status: 'TERISI', patientId: 'PAT-005', updatedAt: '2026-09-27 16:45' },
  { id: 'BED-MEL-104-2', nomorBed: 'B-104-2', kamarId: 'K-MEL-104', ruanganId: 'R-MELATI', status: 'MAINTENANCE', catatanMaintenance: 'Perbaikan panel oksigen dinding', updatedAt: '2026-09-29 13:00' },

  // Mawar (10 beds)
  { id: 'BED-MAW-201-1', nomorBed: 'B-201-1', kamarId: 'K-MAW-201', ruanganId: 'R-MAWAR', status: 'TERISI', patientId: 'PAT-006', updatedAt: '2026-09-29 08:00' },
  { id: 'BED-MAW-201-2', nomorBed: 'B-201-2', kamarId: 'K-MAW-201', ruanganId: 'R-MAWAR', status: 'TERISI', patientId: 'PAT-007', updatedAt: '2026-09-28 10:30' },
  { id: 'BED-MAW-201-3', nomorBed: 'B-201-3', kamarId: 'K-MAW-201', ruanganId: 'R-MAWAR', status: 'AKAN_PINDAH', patientId: 'PAT-008', updatedAt: '2026-09-29 15:40' },
  { id: 'BED-MAW-201-4', nomorBed: 'B-201-4', kamarId: 'K-MAW-201', ruanganId: 'R-MAWAR', status: 'KOSONG', updatedAt: '2026-09-30 07:00' },
  { id: 'BED-MAW-202-1', nomorBed: 'B-202-1', kamarId: 'K-MAW-202', ruanganId: 'R-MAWAR', status: 'TERISI', patientId: 'PAT-009', updatedAt: '2026-09-29 09:20' },
  { id: 'BED-MAW-202-2', nomorBed: 'B-202-2', kamarId: 'K-MAW-202', ruanganId: 'R-MAWAR', status: 'TERISI', patientId: 'PAT-010', updatedAt: '2026-09-27 11:50' },
  { id: 'BED-MAW-202-3', nomorBed: 'B-202-3', kamarId: 'K-MAW-202', ruanganId: 'R-MAWAR', status: 'KOSONG', updatedAt: '2026-09-30 05:40' },
  { id: 'BED-MAW-202-4', nomorBed: 'B-202-4', kamarId: 'K-MAW-202', ruanganId: 'R-MAWAR', status: 'BOOKING', bookingNote: 'Pasien Bedah Pasca Operasi Appendectomy', updatedAt: '2026-09-30 10:15' },
  { id: 'BED-MAW-203-1', nomorBed: 'B-203-1', kamarId: 'K-MAW-203', ruanganId: 'R-MAWAR', status: 'TERISI', patientId: 'PAT-011', updatedAt: '2026-09-30 08:10' },
  { id: 'BED-MAW-203-2', nomorBed: 'B-203-2', kamarId: 'K-MAW-203', ruanganId: 'R-MAWAR', status: 'AKAN_PULANG', patientId: 'PAT-012', updatedAt: '2026-09-26 14:00' },

  // Teratai Kelas 3 (12 beds)
  { id: 'BED-TER-301-1', nomorBed: 'B-301-1', kamarId: 'K-TER-301', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-013', updatedAt: '2026-09-29 11:00' },
  { id: 'BED-TER-301-2', nomorBed: 'B-301-2', kamarId: 'K-TER-301', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-014', updatedAt: '2026-09-28 17:30' },
  { id: 'BED-TER-301-3', nomorBed: 'B-301-3', kamarId: 'K-TER-301', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-015', updatedAt: '2026-09-30 07:15' },
  { id: 'BED-TER-301-4', nomorBed: 'B-301-4', kamarId: 'K-TER-301', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-016', updatedAt: '2026-09-27 13:10' },
  { id: 'BED-TER-301-5', nomorBed: 'B-301-5', kamarId: 'K-TER-301', ruanganId: 'R-TERATAI', status: 'AKAN_PULANG', patientId: 'PAT-017', updatedAt: '2026-09-25 09:00' },
  { id: 'BED-TER-301-6', nomorBed: 'B-301-6', kamarId: 'K-TER-301', ruanganId: 'R-TERATAI', status: 'KOSONG', updatedAt: '2026-09-30 06:00' },

  { id: 'BED-TER-302-1', nomorBed: 'B-302-1', kamarId: 'K-TER-302', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-018', updatedAt: '2026-09-28 14:20' },
  { id: 'BED-TER-302-2', nomorBed: 'B-302-2', kamarId: 'K-TER-302', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-019', updatedAt: '2026-09-29 18:30' },
  { id: 'BED-TER-302-3', nomorBed: 'B-302-3', kamarId: 'K-TER-302', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-020', updatedAt: '2026-09-26 12:00' },
  { id: 'BED-TER-302-4', nomorBed: 'B-302-4', kamarId: 'K-TER-302', ruanganId: 'R-TERATAI', status: 'KOSONG', updatedAt: '2026-09-30 08:00' },
  { id: 'BED-TER-302-5', nomorBed: 'B-302-5', kamarId: 'K-TER-302', ruanganId: 'R-TERATAI', status: 'BOOKING', bookingNote: 'Pasien Dialisis IGD rujukan', updatedAt: '2026-09-30 11:20' },
  { id: 'BED-TER-302-6', nomorBed: 'B-302-6', kamarId: 'K-TER-302', ruanganId: 'R-TERATAI', status: 'TERISI', patientId: 'PAT-021', updatedAt: '2026-09-30 01:30' },

  // Anggrek VIP (6 beds)
  { id: 'BED-ANG-401-1', nomorBed: 'VIP-401', kamarId: 'K-ANG-401', ruanganId: 'R-ANGGREK', status: 'TERISI', patientId: 'PAT-022', updatedAt: '2026-09-29 14:00' },
  { id: 'BED-ANG-402-1', nomorBed: 'VIP-402', kamarId: 'K-ANG-402', ruanganId: 'R-ANGGREK', status: 'TERISI', patientId: 'PAT-023', updatedAt: '2026-09-28 16:00' },
  { id: 'BED-ANG-403-1', nomorBed: 'VIP-403', kamarId: 'K-ANG-403', ruanganId: 'R-ANGGREK', status: 'KOSONG', updatedAt: '2026-09-30 09:00' },
  { id: 'BED-ANG-404-1', nomorBed: 'VIP-404', kamarId: 'K-ANG-404', ruanganId: 'R-ANGGREK', status: 'AKAN_PULANG', patientId: 'PAT-024', updatedAt: '2026-09-27 10:15' },
  { id: 'BED-ANG-405-1', nomorBed: 'VIP-405', kamarId: 'K-ANG-405', ruanganId: 'R-ANGGREK', status: 'TERISI', patientId: 'PAT-025', updatedAt: '2026-09-30 07:45' },
  { id: 'BED-ANG-406-1', nomorBed: 'VIP-406', kamarId: 'K-ANG-406', ruanganId: 'R-ANGGREK', status: 'BOOKING', bookingNote: 'Pasien Eksekutif dr. Suryanto Sp.PD', updatedAt: '2026-09-30 10:00' },

  // Edelweiss VVIP (4 beds)
  { id: 'BED-EDL-501-1', nomorBed: 'VVIP-501', kamarId: 'K-EDL-501', ruanganId: 'R-EDELWEISS', status: 'TERISI', patientId: 'PAT-026', updatedAt: '2026-09-28 11:20' },
  { id: 'BED-EDL-502-1', nomorBed: 'VVIP-502', kamarId: 'K-EDL-502', ruanganId: 'R-EDELWEISS', status: 'KOSONG', updatedAt: '2026-09-30 08:30' },
  { id: 'BED-EDL-503-1', nomorBed: 'VVIP-503', kamarId: 'K-EDL-503', ruanganId: 'R-EDELWEISS', status: 'TERISI', patientId: 'PAT-027', updatedAt: '2026-09-29 19:00' },
  { id: 'BED-EDL-504-1', nomorBed: 'VVIP-504', kamarId: 'K-EDL-504', ruanganId: 'R-EDELWEISS', status: 'KOSONG', updatedAt: '2026-09-30 06:00' },

  // ICU (6 beds)
  { id: 'BED-ICU-601-1', nomorBed: 'ICU-01', kamarId: 'K-ICU-601', ruanganId: 'R-ICU', status: 'TERISI', patientId: 'PAT-028', updatedAt: '2026-09-27 03:00' },
  { id: 'BED-ICU-601-2', nomorBed: 'ICU-02', kamarId: 'K-ICU-601', ruanganId: 'R-ICU', status: 'TERISI', patientId: 'PAT-029', updatedAt: '2026-09-28 08:45' },
  { id: 'BED-ICU-601-3', nomorBed: 'ICU-03', kamarId: 'K-ICU-601', ruanganId: 'R-ICU', status: 'TERISI', patientId: 'PAT-030', updatedAt: '2026-09-29 12:30' },
  { id: 'BED-ICU-602-1', nomorBed: 'ICU-04', kamarId: 'K-ICU-602', ruanganId: 'R-ICU', status: 'TERISI', patientId: 'PAT-031', updatedAt: '2026-09-30 02:15' },
  { id: 'BED-ICU-602-2', nomorBed: 'ICU-05', kamarId: 'K-ICU-602', ruanganId: 'R-ICU', status: 'AKAN_PINDAH', patientId: 'PAT-032', updatedAt: '2026-09-26 14:00' },
  { id: 'BED-ICU-602-3', nomorBed: 'ICU-06', kamarId: 'K-ICU-602', ruanganId: 'R-ICU', status: 'KOSONG', updatedAt: '2026-09-30 10:00' },

  // Isolasi Flamboyan (6 beds)
  { id: 'BED-ISO-701-1', nomorBed: 'ISO-01', kamarId: 'K-ISO-701', ruanganId: 'R-ISOLASI', status: 'TERISI', patientId: 'PAT-033', updatedAt: '2026-09-28 17:00' },
  { id: 'BED-ISO-701-2', nomorBed: 'ISO-02', kamarId: 'K-ISO-701', ruanganId: 'R-ISOLASI', status: 'KOSONG', updatedAt: '2026-09-30 07:00' },
  { id: 'BED-ISO-702-1', nomorBed: 'ISO-03', kamarId: 'K-ISO-702', ruanganId: 'R-ISOLASI', status: 'TERISI', patientId: 'PAT-034', updatedAt: '2026-09-29 09:00' },
  { id: 'BED-ISO-702-2', nomorBed: 'ISO-04', kamarId: 'K-ISO-702', ruanganId: 'R-ISOLASI', status: 'KOSONG', updatedAt: '2026-09-30 08:00' },
  { id: 'BED-ISO-703-1', nomorBed: 'ISO-05', kamarId: 'K-ISO-703', ruanganId: 'R-ISOLASI', status: 'MAINTENANCE', catatanMaintenance: 'Sterilisasi ruangan pasca dekontaminasi', updatedAt: '2026-09-29 16:00' },
  { id: 'BED-ISO-703-2', nomorBed: 'ISO-06', kamarId: 'K-ISO-703', ruanganId: 'R-ISOLASI', status: 'KOSONG', updatedAt: '2026-09-30 06:30' },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'PAT-001',
    noRm: 'RM-491021',
    namaPasien: 'Tn. Joko Sasongko',
    nik: '3171092801750002',
    jenisKelamin: 'L',
    tanggalLahir: '1975-01-28',
    umur: 51,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '10:30',
    ruanganId: 'R-MELATI',
    kamarId: 'K-MEL-101',
    bedId: 'BED-MEL-101-1',
    dokterPj: 'dr. Budi Setiawan, Sp.PD',
    diagnosaMasuk: 'Gastroenteritis Akut Dehidrasi Sedang',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Observasi cairan parenteral, toleransi diet lunak baik.',
  },
  {
    id: 'PAT-002',
    noRm: 'RM-492150',
    namaPasien: 'Ny. Siti Nurjanah',
    nik: '3172085204800004',
    jenisKelamin: 'P',
    tanggalLahir: '1980-04-12',
    umur: 46,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '11:15',
    ruanganId: 'R-MELATI',
    kamarId: 'K-MEL-101',
    bedId: 'BED-MEL-101-2',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Demam Berdarah Dengue (DBD) Derajat II',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Trombosit 85.000, rencana cek lab serial sore ini.',
  },
  {
    id: 'PAT-003',
    noRm: 'RM-488920',
    namaPasien: 'Tn. Ahmad Fauzi',
    nik: '3173041908680001',
    jenisKelamin: 'L',
    tanggalLahir: '1968-08-19',
    umur: 58,
    jaminan: 'Asuransi Swasta',
    tanggalMasuk: '2026-09-26',
    jamMasuk: '14:00',
    ruanganId: 'R-MELATI',
    kamarId: 'K-MEL-102',
    bedId: 'BED-MEL-102-1',
    dokterPj: 'dr. Ahmad Dahlan, Sp.P',
    diagnosaMasuk: 'Pneumonia Komuniti Perbaikan Klinis',
    status: 'AKTIF',
    rencanaPulang: true,
    tanggalRencanaPulang: '2026-09-30',
    jamRencanaPulang: '14:00',
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Dokter sudah visit acc pulang, menunggu farmasi rawat jalan.',
  },
  {
    id: 'PAT-004',
    noRm: 'RM-493012',
    namaPasien: 'An. Muhammad Rayhan',
    nik: '3174092102140003',
    jenisKelamin: 'L',
    tanggalLahir: '2014-02-21',
    umur: 12,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-30',
    jamMasuk: '09:20',
    ruanganId: 'R-MELATI',
    kamarId: 'K-MEL-103',
    bedId: 'BED-MEL-103-1',
    dokterPj: 'dr. Citra Lestari, Sp.A',
    diagnosaMasuk: 'Febris Konvulsi Sederhana',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'BELUM_DICOCOKKAN',
    catatan: 'Pasien baru masuk dari IGD pagi ini. Terpasang IV line infus D5 1/4 NS.',
  },
  {
    id: 'PAT-005',
    noRm: 'RM-487611',
    namaPasien: 'Ny. Endang Triastuti',
    nik: '3175056703620005',
    jenisKelamin: 'P',
    tanggalLahir: '1962-03-27',
    umur: 64,
    jaminan: 'Umum / Mandiri',
    tanggalMasuk: '2026-09-27',
    jamMasuk: '16:45',
    ruanganId: 'R-MELATI',
    kamarId: 'K-MEL-104',
    bedId: 'BED-MEL-104-1',
    dokterPj: 'dr. Surya Dharma, Sp.OT',
    diagnosaMasuk: 'Post ORIF Radius Dextra H-3',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Mobilisasi bertahap, perawatan luka operasi kering.',
  },
  // Mawar
  {
    id: 'PAT-006',
    noRm: 'RM-490234',
    namaPasien: 'Tn. Hendra Saputra',
    nik: '3201081507850001',
    jenisKelamin: 'L',
    tanggalLahir: '1985-07-15',
    umur: 41,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '08:00',
    ruanganId: 'R-MAWAR',
    kamarId: 'K-MAW-201',
    bedId: 'BED-MAW-201-1',
    dokterPj: 'dr. Budi Setiawan, Sp.PD',
    diagnosaMasuk: 'Ulkus Peptikum ec Suspek NSAID',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Terapi PPI injeksi, keluhan mual berkurang.',
  },
  {
    id: 'PAT-007',
    noRm: 'RM-489991',
    namaPasien: 'Ny. Maria Magdalena',
    nik: '3171024509790003',
    jenisKelamin: 'P',
    tanggalLahir: '1979-09-05',
    umur: 47,
    jaminan: 'Asuransi Swasta',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '10:30',
    ruanganId: 'R-MAWAR',
    kamarId: 'K-MAW-201',
    bedId: 'BED-MAW-201-2',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Hipertensi Urgensi + Cephalgia',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Tekanan darah terkontrol 135/85 mmHg.',
  },
  {
    id: 'PAT-008',
    noRm: 'RM-491873',
    namaPasien: 'Tn. Dedi Kusnadi',
    nik: '3172031105700002',
    jenisKelamin: 'L',
    tanggalLahir: '1970-05-11',
    umur: 56,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '15:40',
    ruanganId: 'R-MAWAR',
    kamarId: 'K-MAW-201',
    bedId: 'BED-MAW-201-3',
    dokterPj: 'dr. Bambang Irawan, Sp.JP',
    diagnosaMasuk: 'NSTEMI Akut Onset 12 Jam',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: true,
    ruanganTujuanPindah: 'ICU (Intensive Care Unit)',
    statusRekonsiliasi: 'SELISIH',
    catatan: 'Perburukan sesak nafas, rencana mutasi ke ICU menunggu bed kosong.',
  },
  {
    id: 'PAT-009',
    noRm: 'RM-492500',
    namaPasien: 'Ny. Sri Rahayu',
    nik: '3173065203830006',
    jenisKelamin: 'P',
    tanggalLahir: '1983-03-12',
    umur: 43,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '09:20',
    ruanganId: 'R-MAWAR',
    kamarId: 'K-MAW-202',
    bedId: 'BED-MAW-202-1',
    dokterPj: 'dr. Citra Lestari, Sp.A',
    diagnosaMasuk: 'Kolelitiasis Simtomatik',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Konsul Bedah Digestif dijadwalkan besok pagi.',
  },
  {
    id: 'PAT-010',
    noRm: 'RM-488102',
    namaPasien: 'Tn. Agus Salim',
    nik: '3174011808650001',
    jenisKelamin: 'L',
    tanggalLahir: '1965-08-18',
    umur: 61,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-27',
    jamMasuk: '11:50',
    ruanganId: 'R-MAWAR',
    kamarId: 'K-MAW-202',
    bedId: 'BED-MAW-202-2',
    dokterPj: 'dr. Budi Setiawan, Sp.PD',
    diagnosaMasuk: 'Diabetes Melitus Tipe 2 Hiperglikemia',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Regulasi gula darah dengan basal bolus.',
  },
  {
    id: 'PAT-011',
    noRm: 'RM-493108',
    namaPasien: 'Tn. Rudy Hermawan',
    nik: '3175022204770003',
    jenisKelamin: 'L',
    tanggalLahir: '1977-04-22',
    umur: 49,
    jaminan: 'Umum / Mandiri',
    tanggalMasuk: '2026-09-30',
    jamMasuk: '08:10',
    ruanganId: 'R-MAWAR',
    kamarId: 'K-MAW-203',
    bedId: 'BED-MAW-203-1',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Dispepsia Fungsional Berat',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'BELUM_DICOCOKKAN',
    catatan: 'Baru pindah dari ruang observasi IGD.',
  },
  {
    id: 'PAT-012',
    noRm: 'RM-486710',
    namaPasien: 'Ny. Aminah Kusuma',
    nik: '3171074812600002',
    jenisKelamin: 'P',
    tanggalLahir: '1960-12-08',
    umur: 65,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-26',
    jamMasuk: '14:00',
    ruanganId: 'R-MAWAR',
    kamarId: 'K-MAW-203',
    bedId: 'BED-MAW-203-2',
    dokterPj: 'dr. Ahmad Dahlan, Sp.P',
    diagnosaMasuk: 'Asma Bronkiale Eksaserbasi Sedang Teratasi',
    status: 'AKTIF',
    rencanaPulang: true,
    tanggalRencanaPulang: '2026-09-30',
    jamRencanaPulang: '13:00',
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Keluarga sedang mengurus rincian billing di loket admisi.',
  },
  // Teratai Kelas 3
  {
    id: 'PAT-013',
    noRm: 'RM-491200',
    namaPasien: 'Tn. Slamet Riyadi',
    nik: '3202051206720005',
    jenisKelamin: 'L',
    tanggalLahir: '1972-06-12',
    umur: 54,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '11:00',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-301',
    bedId: 'BED-TER-301-1',
    dokterPj: 'dr. Surya Dharma, Sp.OT',
    diagnosaMasuk: 'Fraktur Clavicula Dextra Closed',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Pasang arm sling, observasi tanda neurovaskuler perifer.',
  },
  {
    id: 'PAT-014',
    noRm: 'RM-490512',
    namaPasien: 'Ny. Kartini Wati',
    nik: '3171095504780004',
    jenisKelamin: 'P',
    tanggalLahir: '1978-04-15',
    umur: 48,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '17:30',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-301',
    bedId: 'BED-TER-301-2',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Anemia Gravis ec Menorrhagia',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Transfusi PRC kantong ke-2 selesai, evaluasi Hb post transfusi besok.',
  },
  {
    id: 'PAT-015',
    noRm: 'RM-492980',
    namaPasien: 'Tn. Wahyu Hidayat',
    nik: '3172081909890001',
    jenisKelamin: 'L',
    tanggalLahir: '1989-09-19',
    umur: 37,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-30',
    jamMasuk: '07:15',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-301',
    bedId: 'BED-TER-301-3',
    dokterPj: 'dr. Budi Setiawan, Sp.PD',
    diagnosaMasuk: 'Suspek Demam Tifoid',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Diet lunak rendah serat, suhu masih subfebris 38.1 C.',
  },
  {
    id: 'PAT-016',
    noRm: 'RM-488421',
    namaPasien: 'Ny. Rohana',
    nik: '3173046101660002',
    jenisKelamin: 'P',
    tanggalLahir: '1966-01-21',
    umur: 60,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-27',
    jamMasuk: '13:10',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-301',
    bedId: 'BED-TER-301-4',
    dokterPj: 'dr. Ahmad Dahlan, Sp.P',
    diagnosaMasuk: 'TB Paru Kasus Baru On OAT Hari Ke-4',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Edukasi kepatuhan minum obat dan etika batuk.',
  },
  {
    id: 'PAT-017',
    noRm: 'RM-485901',
    namaPasien: 'Tn. Mulyadi Saputro',
    nik: '3174031502740003',
    jenisKelamin: 'L',
    tanggalLahir: '1974-02-15',
    umur: 52,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-25',
    jamMasuk: '09:00',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-301',
    bedId: 'BED-TER-301-5',
    dokterPj: 'dr. Surya Dharma, Sp.OT',
    diagnosaMasuk: 'Post Debridement Ulkus Diabetikum Sinistra',
    status: 'AKTIF',
    rencanaPulang: true,
    tanggalRencanaPulang: '2026-09-30',
    jamRencanaPulang: '12:00',
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Edukasi perawatan luka di rumah, kontrol Poli Bedah 3 hari lagi.',
  },
  {
    id: 'PAT-018',
    noRm: 'RM-490199',
    namaPasien: 'Ny. Dewi Sartika',
    nik: '3175084910810001',
    jenisKelamin: 'P',
    tanggalLahir: '1981-10-09',
    umur: 44,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '14:20',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-302',
    bedId: 'BED-TER-302-1',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Vertigo Perifer Berat',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Mual muntah sudah terkontrol, latihan Brandt-Daroff.',
  },
  {
    id: 'PAT-019',
    noRm: 'RM-491650',
    namaPasien: 'Tn. Arif Wibowo',
    nik: '3171032506880004',
    jenisKelamin: 'L',
    tanggalLahir: '1988-06-25',
    umur: 38,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '18:30',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-302',
    bedId: 'BED-TER-302-2',
    dokterPj: 'dr. Budi Setiawan, Sp.PD',
    diagnosaMasuk: 'Kolik Renal Sinistra ec Urolitiasis',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Spasme berkurang, banyak minum air putih.',
  },
  {
    id: 'PAT-020',
    noRm: 'RM-487120',
    namaPasien: 'Ny. Fatimah Az-Zahra',
    nik: '3172076008670002',
    jenisKelamin: 'P',
    tanggalLahir: '1967-08-20',
    umur: 59,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-26',
    jamMasuk: '12:00',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-302',
    bedId: 'BED-TER-302-3',
    dokterPj: 'dr. Ahmad Dahlan, Sp.P',
    diagnosaMasuk: 'PPOK Eksaserbasi Akut',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Nebulisasi combivent per 8 jam, nasal kanul 3 lpm.',
  },
  {
    id: 'PAT-021',
    noRm: 'RM-492801',
    namaPasien: 'Tn. Supardi',
    nik: '3173091103590001',
    jenisKelamin: 'L',
    tanggalLahir: '1959-03-11',
    umur: 67,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-30',
    jamMasuk: '01:30',
    ruanganId: 'R-TERATAI',
    kamarId: 'K-TER-302',
    bedId: 'BED-TER-302-6',
    dokterPj: 'dr. Surya Dharma, Sp.OT',
    diagnosaMasuk: 'Luka Bakar Combustio Grade II 15%',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'BELUM_DICOCOKKAN',
    catatan: 'Masuk dini hari via IGD. Resusitasi cairan formula Parkland.',
  },
  // VIP Anggrek
  {
    id: 'PAT-022',
    noRm: 'RM-491410',
    namaPasien: 'Tn. Ir. Rahmat Hidayat, M.T.',
    nik: '3174081011680005',
    jenisKelamin: 'L',
    tanggalLahir: '1968-11-10',
    umur: 57,
    jaminan: 'Asuransi Swasta',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '14:00',
    ruanganId: 'R-ANGGREK',
    kamarId: 'K-ANG-401',
    bedId: 'BED-ANG-401-1',
    dokterPj: 'dr. Bambang Irawan, Sp.JP',
    diagnosaMasuk: 'Angina Pektoris Stabil Evaluasi Angiografi',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Persiapan kateterisasi jantung hari Kamis.',
  },
  {
    id: 'PAT-023',
    noRm: 'RM-489811',
    namaPasien: 'Ny. Dr. Hj. Nurul Huda',
    nik: '3175045405730002',
    jenisKelamin: 'P',
    tanggalLahir: '1973-05-14',
    umur: 53,
    jaminan: 'Asuransi Swasta',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '16:00',
    ruanganId: 'R-ANGGREK',
    kamarId: 'K-ANG-402',
    bedId: 'BED-ANG-402-1',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Hipertiroid Grave Disease Krisis Terkendali',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Tremor berkurang, nadi 84x/m.',
  },
  {
    id: 'PAT-024',
    noRm: 'RM-487900',
    namaPasien: 'Tn. Kevin Sanjaya',
    nik: '3171012909930001',
    jenisKelamin: 'L',
    tanggalLahir: '1993-09-29',
    umur: 33,
    jaminan: 'Asuransi Swasta',
    tanggalMasuk: '2026-09-27',
    jamMasuk: '10:15',
    ruanganId: 'R-ANGGREK',
    kamarId: 'K-ANG-404',
    bedId: 'BED-ANG-404-1',
    dokterPj: 'dr. Surya Dharma, Sp.OT',
    diagnosaMasuk: 'Post Arthroscopy ACL Reconstruction Dextra',
    status: 'AKTIF',
    rencanaPulang: true,
    tanggalRencanaPulang: '2026-09-30',
    jamRencanaPulang: '15:00',
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Fisioterapi latihan jalan dengan kruk sukses, siap KRS.',
  },
  {
    id: 'PAT-025',
    noRm: 'RM-492770',
    namaPasien: 'Ny. Veronica Tan',
    nik: '3172054110820003',
    jenisKelamin: 'P',
    tanggalLahir: '1982-10-01',
    umur: 43,
    jaminan: 'Umum / Mandiri',
    tanggalMasuk: '2026-09-30',
    jamMasuk: '07:45',
    ruanganId: 'R-ANGGREK',
    kamarId: 'K-ANG-405',
    bedId: 'BED-ANG-405-1',
    dokterPj: 'dr. Citra Lestari, Sp.A',
    diagnosaMasuk: 'Dengue Fever Warning Sign',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'BELUM_DICOCOKKAN',
    catatan: 'Permintaan naik kelas dari rawat umum.',
  },
  // VVIP Edelweiss
  {
    id: 'PAT-026',
    noRm: 'RM-489001',
    namaPasien: 'Tn. H. Mochtar Effendy',
    nik: '3173010506540001',
    jenisKelamin: 'L',
    tanggalLahir: '1954-06-05',
    umur: 72,
    jaminan: 'Umum / Mandiri',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '11:20',
    ruanganId: 'R-EDELWEISS',
    kamarId: 'K-EDL-501',
    bedId: 'BED-EDL-501-1',
    dokterPj: 'dr. Bambang Irawan, Sp.JP',
    diagnosaMasuk: 'Congestive Heart Failure NYHA FC III',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Restriksi cairan 1200 ml/24 jam, diuresis adekuat.',
  },
  {
    id: 'PAT-027',
    noRm: 'RM-491950',
    namaPasien: 'Ny. Grace Natalie',
    nik: '3174094208850002',
    jenisKelamin: 'P',
    tanggalLahir: '1985-08-02',
    umur: 41,
    jaminan: 'Asuransi Swasta',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '19:00',
    ruanganId: 'R-EDELWEISS',
    kamarId: 'K-EDL-503',
    bedId: 'BED-EDL-503-1',
    dokterPj: 'dr. Budi Setiawan, Sp.PD',
    diagnosaMasuk: 'Severe Migraine with Aura + Dehidrasi Ringan',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Pencahayaan kamar redup sesuai instruksi neurologi.',
  },
  // ICU
  {
    id: 'PAT-028',
    noRm: 'RM-487050',
    namaPasien: 'Tn. Bagus Santoso',
    nik: '3175021404690001',
    jenisKelamin: 'L',
    tanggalLahir: '1969-04-14',
    umur: 57,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-27',
    jamMasuk: '03:00',
    ruanganId: 'R-ICU',
    kamarId: 'K-ICU-601',
    bedId: 'BED-ICU-601-1',
    dokterPj: 'dr. Bambang Irawan, Sp.JP',
    diagnosaMasuk: 'Syok Kardiogenik ec STEMI Anterior Luas',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'On Dobutamin 5 mcg/kg/menit, monitoring CVP ketat.',
  },
  {
    id: 'PAT-029',
    noRm: 'RM-488650',
    namaPasien: 'Ny. Halimah binti Yahya',
    nik: '3171066512630004',
    jenisKelamin: 'P',
    tanggalLahir: '1963-12-25',
    umur: 62,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '08:45',
    ruanganId: 'R-ICU',
    kamarId: 'K-ICU-601',
    bedId: 'BED-ICU-601-2',
    dokterPj: 'dr. Ahmad Dahlan, Sp.P',
    diagnosaMasuk: 'ARDS ec Sepsis Berat Fokus Pulmo',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Terpasang Ventilator Mekanik Mode SIMV-PC, PEEP 8.',
  },
  {
    id: 'PAT-030',
    noRm: 'RM-490890',
    namaPasien: 'Tn. Jonathan Kristi',
    nik: '3172010903900005',
    jenisKelamin: 'L',
    tanggalLahir: '1990-03-09',
    umur: 36,
    jaminan: 'Asuransi Swasta',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '12:30',
    ruanganId: 'R-ICU',
    kamarId: 'K-ICU-601',
    bedId: 'BED-ICU-601-3',
    dokterPj: 'dr. Surya Dharma, Sp.OT',
    diagnosaMasuk: 'Politrauma Cedera Kepala Berat (GCS 7)',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Post trepanasi evakuasi EDH, sedasi Midazolam kontinu.',
  },
  {
    id: 'PAT-031',
    noRm: 'RM-492911',
    namaPasien: 'Ny. Ratna Galih',
    nik: '3173055106840003',
    jenisKelamin: 'P',
    tanggalLahir: '1984-06-11',
    umur: 42,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-30',
    jamMasuk: '02:15',
    ruanganId: 'R-ICU',
    kamarId: 'K-ICU-602',
    bedId: 'BED-ICU-602-1',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Ketoasidosis Diabetikum (KAD) On Resusitasi',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Infus Insulin pump 0.1 IU/kg/jam, pH darah 7.22.',
  },
  {
    id: 'PAT-032',
    noRm: 'RM-486001',
    namaPasien: 'Tn. Ruslan Abdulgani',
    nik: '3174020301580001',
    jenisKelamin: 'L',
    tanggalLahir: '1958-01-03',
    umur: 68,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-26',
    jamMasuk: '14:00',
    ruanganId: 'R-ICU',
    kamarId: 'K-ICU-602',
    bedId: 'BED-ICU-602-2',
    dokterPj: 'dr. Ahmad Dahlan, Sp.P',
    diagnosaMasuk: 'Post Extubasi H-1 Eksaserbasi Asma Berat',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: true,
    ruanganTujuanPindah: 'Ruang Melati (Kelas 1)',
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Kondisi stabil, weaning ventilator tuntas, siap step-down ke bangsal Melati.',
  },
  // Isolasi Flamboyan
  {
    id: 'PAT-033',
    noRm: 'RM-489332',
    namaPasien: 'Tn. Dani Iskandar',
    nik: '3175061907760002',
    jenisKelamin: 'L',
    tanggalLahir: '1976-07-19',
    umur: 50,
    jaminan: 'BPJS Kesehatan',
    tanggalMasuk: '2026-09-28',
    jamMasuk: '17:00',
    ruanganId: 'R-ISOLASI',
    kamarId: 'K-ISO-701',
    bedId: 'BED-ISO-701-1',
    dokterPj: 'dr. Ahmad Dahlan, Sp.P',
    diagnosaMasuk: 'TB Paru MDR (Multi Drug Resistant)',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Kamar tekanan negatif aktif, APD level 2 untuk petugas.',
  },
  {
    id: 'PAT-034',
    noRm: 'RM-491555',
    namaPasien: 'Ny. Tiara Andini',
    nik: '3171084209950007',
    jenisKelamin: 'P',
    tanggalLahir: '1995-09-02',
    umur: 31,
    jaminan: 'Umum / Mandiri',
    tanggalMasuk: '2026-09-29',
    jamMasuk: '09:00',
    ruanganId: 'R-ISOLASI',
    kamarId: 'K-ISO-702',
    bedId: 'BED-ISO-702-1',
    dokterPj: 'dr. Farida Rahma, Sp.PD',
    diagnosaMasuk: 'Mpox Suspek Konfirmasi Lab Isolasi',
    status: 'AKTIF',
    rencanaPulang: false,
    rencanaPindah: false,
    statusRekonsiliasi: 'SESUAI',
    catatan: 'Lesi kulit vesikular mengering, isolasi droplet dan kontak.',
  },
];

export const INITIAL_MOVEMENTS: PatientMovement[] = [
  {
    id: 'MOV-20260930-001',
    waktuMutasi: '2026-09-30 09:20:15',
    pasienId: 'PAT-004',
    namaPasien: 'An. Muhammad Rayhan',
    noRm: 'RM-493012',
    dariRuanganId: 'IGD',
    dariRuanganNama: 'Instalasi Gawat Darurat (IGD)',
    dariKamarId: 'TRIAGE',
    dariKamarNama: 'Kamar Tindakan IGD',
    dariBedId: 'BED-IGD-03',
    dariNomorBed: 'IGD-03',
    keRuanganId: 'R-MELATI',
    keRuanganNama: 'Ruang Melati (Kelas 1)',
    keKamarId: 'K-MEL-103',
    keKamarNama: 'Kamar 103',
    keBedId: 'BED-MEL-103-1',
    keNomorBed: 'B-103-1',
    jenisMutasi: 'Masuk Rawat Inap',
    alasanMutasi: 'Rawat inap lanjutan pasca stabilisasi kejang demam di IGD',
    petugas: 'Sdr. Dimas Admisi & Ns. Ratna Dewi',
    rolePetugas: 'Admisi / TPPRI',
    statusVerifikasi: 'Terverifikasi',
    timestamp: '2026-09-30T09:20:15+07:00',
  },
  {
    id: 'MOV-20260930-002',
    waktuMutasi: '2026-09-30 08:10:00',
    pasienId: 'PAT-011',
    namaPasien: 'Tn. Rudy Hermawan',
    noRm: 'RM-493108',
    dariRuanganId: 'IGD',
    dariRuanganNama: 'Instalasi Gawat Darurat (IGD)',
    dariKamarId: 'OBSERVASI',
    dariKamarNama: 'Ruang Observasi IGD',
    dariBedId: 'BED-IGD-08',
    dariNomorBed: 'IGD-08',
    keRuanganId: 'R-MAWAR',
    keRuanganNama: 'Ruang Mawar (Kelas 2)',
    keKamarId: 'K-MAW-203',
    keKamarNama: 'Kamar 203',
    keBedId: 'BED-MAW-203-1',
    keNomorBed: 'B-203-1',
    jenisMutasi: 'Masuk Rawat Inap',
    alasanMutasi: 'Persetujuan rawat inap keluhan nyeri epigastrium hebat',
    petugas: 'Ns. Hendra Wijaya',
    rolePetugas: 'Perawat Ruangan',
    statusVerifikasi: 'Terverifikasi',
    timestamp: '2026-09-30T08:10:00+07:00',
  },
  {
    id: 'MOV-20260930-003',
    waktuMutasi: '2026-09-30 07:45:22',
    pasienId: 'PAT-025',
    namaPasien: 'Ny. Veronica Tan',
    noRm: 'RM-492770',
    dariRuanganId: 'R-TERATAI',
    dariRuanganNama: 'Ruang Teratai (Kelas 3)',
    dariKamarId: 'K-TER-302',
    dariKamarNama: 'Kamar 302',
    dariBedId: 'BED-TER-302-4',
    dariNomorBed: 'B-302-4',
    keRuanganId: 'R-ANGGREK',
    keRuanganNama: 'Ruang Anggrek (VIP)',
    keKamarId: 'K-ANG-405',
    keKamarNama: 'VIP Suite 405',
    keBedId: 'BED-ANG-405-1',
    keNomorBed: 'VIP-405',
    jenisMutasi: 'Pindah Ruangan',
    alasanMutasi: 'Permintaan pasien/keluarga upgrade kelas ke VIP Suite',
    petugas: 'Ns. Maya Indah',
    rolePetugas: 'Perawat Ruangan',
    statusVerifikasi: 'Terverifikasi',
    timestamp: '2026-09-30T07:45:22+07:00',
  },
  {
    id: 'MOV-20260930-004',
    waktuMutasi: '2026-09-30 06:10:00',
    pasienId: 'PAT-PAST-090',
    namaPasien: 'Tn. Gunawan Prasetyo',
    noRm: 'RM-479100',
    dariRuanganId: 'R-MELATI',
    dariRuanganNama: 'Ruang Melati (Kelas 1)',
    dariKamarId: 'K-MEL-102',
    dariKamarNama: 'Kamar 102',
    dariBedId: 'BED-MEL-102-2',
    dariNomorBed: 'B-102-2',
    keRuanganId: 'HOME',
    keRuanganNama: 'Pulang Ke Rumah',
    keKamarId: '-',
    keKamarNama: '-',
    keBedId: '-',
    keNomorBed: '-',
    jenisMutasi: 'Pulang',
    alasanMutasi: 'Sembuh - KRS atas rekomendasi dr. Ahmad Dahlan, Sp.P',
    petugas: 'Ns. Ratna Dewi',
    rolePetugas: 'Perawat Ruangan',
    statusVerifikasi: 'Terverifikasi',
    timestamp: '2026-09-30T06:10:00+07:00',
  },
  {
    id: 'MOV-20260929-005',
    waktuMutasi: '2026-09-29 20:15:00',
    pasienId: 'PAT-027',
    namaPasien: 'Ny. Grace Natalie',
    noRm: 'RM-491950',
    dariRuanganId: 'IGD',
    dariRuanganNama: 'Instalasi Gawat Darurat (IGD)',
    dariKamarId: 'TRIAGE',
    dariKamarNama: 'Kamar Tindakan IGD',
    dariBedId: 'BED-IGD-01',
    dariNomorBed: 'IGD-01',
    keRuanganId: 'R-EDELWEISS',
    keRuanganNama: 'Ruang Edelweiss (VVIP)',
    keKamarId: 'K-EDL-503',
    keKamarNama: 'Presidential 503',
    keBedId: 'BED-EDL-503-1',
    keNomorBed: 'VVIP-503',
    jenisMutasi: 'Masuk Rawat Inap',
    alasanMutasi: 'Rawat inap VVIP kasus migrain berat',
    petugas: 'Sdr. Dimas Admisi',
    rolePetugas: 'Admisi / TPPRI',
    statusVerifikasi: 'Terverifikasi',
    timestamp: '2026-09-29T20:15:00+07:00',
  },
  {
    id: 'MOV-20260929-006',
    waktuMutasi: '2026-09-29 16:40:00',
    pasienId: 'PAT-008',
    namaPasien: 'Tn. Dedi Kusnadi',
    noRm: 'RM-491873',
    dariRuanganId: 'R-MAWAR',
    dariRuanganNama: 'Ruang Mawar (Kelas 2)',
    dariKamarId: 'K-MAW-201',
    dariKamarNama: 'Kamar 201',
    dariBedId: 'BED-MAW-201-1',
    dariNomorBed: 'B-201-1',
    keRuanganId: 'R-MAWAR',
    keRuanganNama: 'Ruang Mawar (Kelas 2)',
    keKamarId: 'K-MAW-201',
    keKamarNama: 'Kamar 201',
    keBedId: 'BED-MAW-201-3',
    keNomorBed: 'B-201-3',
    jenisMutasi: 'Pindah Bed',
    alasanMutasi: 'Perpindahan bed dekat outlet oksigen utama',
    petugas: 'Ns. Hendra Wijaya',
    rolePetugas: 'Perawat Ruangan',
    statusVerifikasi: 'Terverifikasi',
    timestamp: '2026-09-29T16:40:00+07:00',
  },
];

export const INITIAL_RECONCILIATION: ReconciliationSession[] = [
  {
    id: 'REC-20260930-0800',
    tanggal: '2026-09-30',
    shift: '08.00 WIB',
    ruanganId: 'ALL',
    ruanganNama: 'Semua Ruangan (RS Keseluruhan)',
    petugasRuangan: 'Ns. Ratna Dewi / Ns. Hendra Wijaya',
    petugasAdmisi: 'Sdr. Dimas Kurniawan, A.Md.RMIK',
    petugasRekamMedis: 'Sdri. Anisa Putri, S.ST',
    pasienSistem: 34,
    pasienAktual: 34,
    bedSistem: 52,
    bedAktual: 52,
    selisih: 0,
    status: 'Selesai Diverifikasi',
    catatan: 'Rekonsiliasi pagi shift 08.00 WIB rampung. Seluruh data fisik bangsal cocok dengan data SIMUTASIS.',
    waktuPenyelesaian: '2026-09-30 08:35 WIB',
  },
  {
    id: 'REC-20260930-1400',
    tanggal: '2026-09-30',
    shift: '14.00 WIB',
    ruanganId: 'R-MAWAR',
    ruanganNama: 'Ruang Mawar (Kelas 2)',
    petugasRuangan: 'Ns. Hendra Wijaya',
    petugasAdmisi: 'Sdr. Dimas Kurniawan',
    petugasRekamMedis: 'Sdri. Anisa Putri',
    pasienSistem: 6,
    pasienAktual: 6,
    bedSistem: 10,
    bedAktual: 10,
    selisih: 0,
    status: 'Dalam Proses',
    catatan: 'Sedang verifikasi status rencana mutasi Tn. Dedi Kusnadi ke ICU dan 1 pasien akan pulang.',
  },
  {
    id: 'REC-20260930-2000',
    tanggal: '2026-09-30',
    shift: '20.00 WIB',
    ruanganId: 'ALL',
    ruanganNama: 'Semua Ruangan (RS Keseluruhan)',
    petugasRuangan: 'Tim Jaga Malam',
    petugasAdmisi: 'Petugas Admisi Malam',
    petugasRekamMedis: 'Verifikator Rekam Medis',
    pasienSistem: 34,
    pasienAktual: 0,
    bedSistem: 52,
    bedAktual: 0,
    selisih: 0,
    status: 'Belum',
    catatan: 'Jadwal rekonsiliasi shift malam pukul 20.00 WIB.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-09-30 09:20:15 WIB',
    user: 'Sdr. Dimas Admisi',
    role: 'Admisi / TPPRI',
    action: 'Pasien Masuk (Admission)',
    entity: 'PATIENT',
    dataSebelum: 'Bed B-103-1: KOSONG',
    dataSesudah: 'Bed B-103-1: TERISI (Pasien An. Muhammad Rayhan, RM-493012)',
  },
  {
    id: 'AUD-002',
    timestamp: '2026-09-30 08:35:00 WIB',
    user: 'Sdri. Anisa Putri',
    role: 'Rekam Medis',
    action: 'Selesaikan Rekonsiliasi Shift 08.00 WIB',
    entity: 'RECONCILIATION',
    dataSebelum: 'Status: Dalam Proses',
    dataSesudah: 'Status: Selesai Diverifikasi (Selisih 0)',
  },
  {
    id: 'AUD-003',
    timestamp: '2026-09-30 07:45:22 WIB',
    user: 'Ns. Maya Indah',
    role: 'Perawat Ruangan',
    action: 'Mutasi Pasien Antar Ruang',
    entity: 'MUTATION',
    dataSebelum: 'Ny. Veronica Tan di B-302-4 (R-TERATAI)',
    dataSesudah: 'Ny. Veronica Tan di VIP-405 (R-ANGGREK). Bed lama otomatis KOSONG.',
  },
];
